### ISSUE TITLE
Decide what recipe information we want to show

### ISSUE THREAD

**Issue by joe-dev-public** [vasystus/hungri-la#19]
The spoonacular API returns a lot of recipe information!

https://spoonacular.com/food-api/docs#Get-Recipe-Information

We should probably only show users a limited amount of information, for the purposes of this project :)

**What information should we pick?**

At first glance, I think the following makes sense:

- Title
- Picture
- Servings
- Time required
- Ingredients summary (just a list of ``"name"``s from ``"extendedIngredients"``)
- **Link to original recipe** (I don't think we should try and reproduce the whole recipe on our page!)

**Comment by vasystus** [comment]
Is it possible to return title and link to the recipe? If not then link only.

Servings, time and list of ingredients are not really the main target of the user and the picture is good, but would it be clashing with the gif sticker?

**Comment by joe-dev-public** [comment]
As we just discussed on Zoom, a link to the recipe with the title as the text is good.
