### ISSUE TITLE
Clearer way to insert first child

### ISSUE THREAD

**Issue by oliverjam** [vasystus/hungri-la#60]
https://github.com/vasystus/hungri-la/blob/69d04ef32c48ba9844aaacf712d65bb146d5c0d8/script.js#L67

In modern browsers (i.e. not Internet Explorer) you can use [`out.prepend(fig)`](https://developer.mozilla.org/en-US/docs/Web/API/Element/prepend) to insert a new element as the first child.

(not that your solution is bad, it just took me a second to figure out what it was doing 😅 )

**Comment by joe-dev-public** [comment]
Closed by #68
