### ISSUE TITLE
Opening links in new tab

### ISSUE THREAD

**Issue by oliverjam** [vasystus/hungri-la#61]
https://github.com/vasystus/hungri-la/blob/69d04ef32c48ba9844aaacf712d65bb146d5c0d8/index.html#L42-L43

If you're going to use `target="_blank"` you also need to add `rel="noopener"` (it's a security thing, more info here: https://web.dev/external-anchors-use-rel-noopener/)

I'd also recommend considering the UX of _forcing_ this decision on the user. With a normal link the user always has the choice to open in a new tab (either via right-click menu, cmd-click, middle-click etc). If you do this the user has no choice to open in the same window. This may be correct for the page you're building, it's just good to think through the consequences.

**Comment by vasystus** [comment]
rel="noopener" added
